### ISSUE TITLE
URL voldoet niet aan REST.

### ISSUE THREAD

**Issue by Sir-Fenrir** [TeamFuchsia/BoeteAPI#17]
https://github.com/TeamFuchsia/BoeteAPI/blob/0d8a3e754070186edf981b34e2ad773c8fe07170/src/main/java/nl/fuchsia/controller/PersoonController.java#L40

_/personen/add_ is geen goede REST endpoint. De endpoint moet wijzen naar een _resource_, een _zelfstandig naamwoord_.

Je voert een actie (_POST_) uit op een resource (_/personen_) waarmee je dus een persoon toevoegt aan die resource.

GET /personen -> Haal alle personen op
GET /personen/1234 -> Haal een specifiek persoon op (subresource)
POST /personen -> Voeg een nieuw persoon toe
PUT /personen/1234 -> Update een specifiek persoon
DELETE /personen/1234 -> Verwijder een specifiek persoon

**Comment by NiewoldR** [comment]
Is aangepast.
