### ISSUE TITLE
Project compileert niet.

### ISSUE THREAD

**Issue by Sir-Fenrir** [TeamFuchsia/BoeteAPI#28]
De volgende regel blokkeert het compileren van het project: 
https://github.com/TeamFuchsia/BoeteAPI/blob/ddb95e57d75672c9f18173f435b2dca2bf8876f6/src/main/java/nl/fuchsia/exceptionhandlers/NullException.java#L3

**Comment by NiewoldR** [comment]
Kwam ik net voor de vakantie al achter, staat al een pullrequest voor. Verwijderen van teken en toevoegen van import.
